
###
GET http://localhost:4000/api/pages

###
GET http://localhost:4000/api/page/1

###
POST http://localhost:4000/api/page
content-type: application/json

{
  "title": "测试",
  "url": "111",
  "content": "2222",
  "urlsCount": 0
}


###
PUT http://localhost:4000/api/page/1
content-type: application/json

{
  "title": "测试",
  "url": "111",
  "content": "2222",
  "urlsCount": 0
}

###
DELETE http://localhost:4000/api/page/1

