# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy

on:
  push:
    branches: [aliyun]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
      # - run: npm i
      # - run: npm run build
      # - uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }} # 服务器host
      #     username: 'root' # 服务器用户名
      #     password: ${{ secrets.PASSWORD }} # 服务器密码
      #     script: | # 运行多行命令
      #       echo "[deploy] 删除老包"
      #       cd /www/wwwroot/hd-crawler
      #       rm -rf dist
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }} # 服务器host
          username: 'root' # 服务器用户名
          password: ${{ secrets.PASSWORD }} # 服务器密码
          source: 'dist,api,api-src,prisma,package.json,package-lock.json' # 需要上传的文件, 多文件使用逗号隔开
          target: '/www/wwwroot/hd-crawler' # 上传到服务器的什么位置
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 服务器host
          username: 'root' # 服务器用户名
          password: ${{ secrets.PASSWORD }} # 服务器密码
          script: | # 运行多行命令，hd_crawler为项目名称，是宝塔生成的
            echo "[deploy] 运行api"
            cd /www/wwwroot/hd-crawler
            npm i
            kill -9 $(ps aux | grep 'api/index.js' | grep -v grep | awk '{print $2}')
            sh /www/server/nodejs/vhost/scripts/hd_crawler.sh
            echo "End"


